pipeline {
  environment {
    PROJECT = "sandbox-io-289003"
    APP_NAME = "Taj-App-1"
    FE_SVC_NAME = "${APP_NAME}-frontend"
    CLUSTER = "jenkins-cd"
    CLUSTER_ZONE = "us-east1-c"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
    JENKINS_CRED = "${PROJECT}"
  }

  agent {
    kubernetes {
      label 'my-agent'
      defaultContainer 'lyej'
      yaml """
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          app: my-agent
      spec:
        serviceAccountName: cd-jenkins
        containers:
        - name: maven
          image: maven
          command:
          - cat
          tty: true
          - name: kubectl
          image: kubectl:latest
          command:
        - name: python
          image: python:latest
          command:
          - cat
          tty: true
      """
    }
  }

stages {

    stage('comp') {
       steps {
        container('maven') {
          sh "pwd"
          }
        }
      }
    }

stage('Run Python') {
      steps {
        container('python') {
          sh 'pip list'
        }
      }
    }
