pipeline {
  environment {
    PROJECT = "sandbox-io-289003"
    APP_NAME = "Taj-App-1"
    FE_SVC_NAME = "${APP_NAME}-frontend"
    CLUSTER = "jenkins-cd"
    CLUSTER_ZONE = "us-east1-d"
    IMAGE_TAG = "gcr.io/${PROJECT}/${APP_NAME}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"
    JENKINS_CRED = "${PROJECT}"
  }

  agent {
    kubernetes {
      label 'taj-agent'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
   components: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: cd-jenkins
  containers:
  - name:  ubuntu
    image:  ubuntu
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
  - name: python
    image: python:3
    command:
    - cat
    tty: true
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
"""
}
  }
  stages {
    stage('Compilation') {
       steps {
        container('ubuntu') {
          sh "echo ${IMAGE_TAG}"
        }
      }
    }
    
    stage('Deployment') {
       steps {
        container('python') {
          sh "pip list"
        }
      }
    }
    stage('Deploy to kubernetes') {
      steps {
        container('kubectl') {
          dir("spring-boot-app") {
           sh "kubectl apply -f deployment.yaml"
         }
        }
      }
    }
  }
}