apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.labels }}
  labels:
    app: {{ .Values.app.labels }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.labels }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}